### ISSUE TITLE
Bigsam - Function Rebalance can deposit above Moneymarket ceiling

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-06-union-finance-update-2-judging#109]
Bigsam

Medium

# Function Rebalance can deposit above Moneymarket ceiling

## Summary

The current implementation of the `rebalance` function in `AssetManager.sol` redistributes tokens among supported money markets. However, it fails to check if the amount to be deposited exceeds the ceiling of the money market, thereby potentially violating one of the core checks of the protocol.

## Vulnerability Detail
The `rebalance` function is designed to redistribute tokens among supported money markets according to specified percentages. However, it does not check if the amount being deposited exceeds the ceiling of any money market, which can lead to deposits above the ceiling limit. This breaks one of the core checks in the protocol that prevents deposits above a money market ceiling.

Here is the current implementation of the `rebalance` function:

```solidity
function rebalance(
    address tokenAddress,
    uint256[] calldata percentages
) external override onlyOwner whenNotPaused nonReentrant {
    IERC20Upgradeable token = IERC20Upgradeable(tokenAddress);
    uint256 tokenSupply = token.balanceOf(address(this));
    uint256 percentagesLength = percentages.length;
    uint256 supportedMoneyMarketsSize = supportedMoneyMarkets.length;

    require(percentagesLength == supportedMoneyMarketsSize, "AssetManager: mismatched input lengths");

    for (uint256 i = 0; i < percentagesLength; i++) {
        IMoneyMarketAdapter moneyMarket = supportedMoneyMarkets[i];
        uint256 amountToDeposit = (tokenSupply * percentages[i]) / 10000;
        if (amountToDeposit == 0) continue;

 @audit>>   amountToDeposit can be greater than  ceiling  >>      token.safeTransfer(address(moneyMarket), amountToDeposit);
        
moneyMarket.deposit(tokenAddress);
    }

    uint256 remainingTokens = token.balanceOf(address(this));

    IMoneyMarketAdapter lastMoneyMarket = supportedMoneyMarkets[supportedMoneyMarketsSize - 1];
    if (remainingTokens > 0) {

       @audit>>   remainingTokens can be greater than ceiling  >>     token.safeTransfer(address(lastMoneyMarket), remainingTokens);

        lastMoneyMarket.deposit(tokenAddress);
    }
}
```

## Impact

Failing to check if the amount to be deposited exceeds the ceiling of the money market can lead to deposits above the ceiling limit. This can result in potential overexposure and liquidity issues in the protocol.

## Code Snippet

https://github.com/sherlock-audit/2024-06-union-finance-update-2/blob/main/union-v2-contracts/contracts/asset/AssetManager.sol#L308

https://github.com/sherlock-audit/2024-06-union-finance-update-2/blob/main/union-v2-contracts/contracts/asset/AssetManager.sol#L561-L563

https://github.com/sherlock-audit/2024-06-union-finance-update-2/blob/main/union-v2-contracts/contracts/asset/AssetManager.sol#L570-L571

https://github.com/sherlock-audit/2024-06-union-finance-update-2/blob/main/union-v2-contracts/contracts/asset/AssetManager.sol#L525-L575
## Tool used

Manual Review

## Recommendation

Add a check to ensure that the amount to be deposited does not exceed the ceiling of the money market. If the amount exceeds the ceiling, the function should revert.

Here is the updated code:

```solidity
  function rebalance(
        address tokenAddress,
        uint256[] calldata percentages
    ) external override onlyAdmin checkMarketSupported(tokenAddress) {
        IERC20Upgradeable token = IERC20Upgradeable(tokenAddress);
        uint256 moneyMarketsLength = moneyMarkets.length;
        uint256 percentagesLength = percentages.length;

        IMoneyMarketAdapter[] memory supportedMoneyMarkets = new IMoneyMarketAdapter[](moneyMarketsLength);
        uint256 supportedMoneyMarketsSize;

        // Loop through each money market and withdraw all the tokens
        for (uint256 i = 0; i < moneyMarketsLength; i++) {
            IMoneyMarketAdapter moneyMarket = moneyMarkets[i];
            if (!moneyMarket.supportsToken(tokenAddress)) continue;
            supportedMoneyMarkets[supportedMoneyMarketsSize] = moneyMarket;
            supportedMoneyMarketsSize++;
            moneyMarket.withdrawAll(tokenAddress, address(this));
        }

        if (percentagesLength + 1 != supportedMoneyMarketsSize) revert NotParity();

        uint256 tokenSupply = token.balanceOf(address(this));

        for (uint256 i = 0; i < percentagesLength; i++) {
            IMoneyMarketAdapter moneyMarket = supportedMoneyMarkets[i];
            uint256 amountToDeposit = (tokenSupply * percentages[i]) / 10000;
            if (amountToDeposit == 0) continue;

 ++       uint256 currentSupply = moneyMarket.getSupply(tokenAddress); // which is 0 since we have withdrawn all
 ++     uint256 ceiling = moneyMarket.ceilingMap(tokenAddress);
 ++      if (currentSupply + amountToDeposit > ceiling) {
 ++         revert("AssetManager: deposit amount exceeds ceiling");
        }
            token.safeTransfer(address(moneyMarket), amountToDeposit);
            moneyMarket.deposit(tokenAddress);
        }

        uint256 remainingTokens = token.balanceOf(address(this));

        IMoneyMarketAdapter lastMoneyMarket = supportedMoneyMarkets[supportedMoneyMarketsSize - 1];
        if (remainingTokens > 0) {
     ++       uint256 currentSupply = lastMoneyMarket.getSupply(tokenAddress); // which is 0 since we have withdrawn all
     ++       uint256 ceiling = lastMoneyMarket.ceilingMap(tokenAddress);
     ++       if (currentSupply + remainingTokens > ceiling) {
     ++       revert("AssetManager: deposit amount exceeds ceiling");
          }
            token.safeTransfer(address(lastMoneyMarket), remainingTokens);
            lastMoneyMarket.deposit(tokenAddress);
        }

        emit LogRebalance(tokenAddress, percentages);
    }

```

**Comment by twicek** [comment]
Escalate
As stated here https://github.com/sherlock-audit/2024-06-union-finance-update-2-judging/issues/98#issuecomment-2240803436, I don't think that going above the ceiling is an issue during a single transaction. At the next transaction, the money market will be skipped because it is above the ceiling. This is as intended.

**Comment by sherlock-admin3** [comment]
> Escalate
> As stated here https://github.com/sherlock-audit/2024-06-union-finance-update-2-judging/issues/98#issuecomment-2240803436, I don't think that going above the ceiling is an issue during a single transaction. At the next transaction, the money market will be skipped because it is above the ceiling. This is as intended.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Tomiwasa0** [comment]
As answered in issue 98, going above the ceiling breaks the money-market invariant which should always hold true. hence a valid medium also.

**Comment by mystery0x** [comment]
Please see comment on #98.

**Comment by vsharma4394** [comment]
Rebalance function can only be called by admin so wouldn't it be admin error is they pass wrong percentages array which could cause the above scenario to happen.

**Comment by Tomiwasa0** [comment]
Moneymarket is an external integration by the protocol hence all invariants pertaining to the market must be maintained by both users and admin.

**Comment by c-plus-plus-equals-c-plus-one** [comment]
I agree with @vsharma4394, because the `rebalance` function is only calleable by the admin.

**Comment by WangSecurity** [comment]
Firstly, since it's called by the admin, then the following rule applies:

> An admin action can break certain assumptions about the functioning of the code. Example: Pausing a collateral causes some users to be unfairly liquidated or any other action causing loss of funds. This is not considered a valid issue

Secondly, it's external protocols and if they allow depositing above the ceiling, then I believe it's their design as expressed in [this comment](https://github.com/sherlock-audit/2024-06-union-finance-update-2-judging/issues/109#issuecomment-2240812098): the transaction that leads to passing ceiling goes through and the next reverts.

Thirdly, I don't see how just passing above the ceiling qualifies for medium severity.

Planning to accept the escalation and invalidate the issue.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [twicek](https://github.com/sherlock-audit/2024-06-union-finance-update-2-judging/issues/109/#issuecomment-2240812098): accepted
