### ISSUE TITLE
hyh - `exchangeRateStored()` decimals are incorrect and misaligned with `exchangeRateCurrent()`

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-union-finance-update-2-judging#110]
hyh

Medium

# `exchangeRateStored()` decimals are incorrect and misaligned with `exchangeRateCurrent()`

## Summary

UToken's `exchangeRateStored()` and `exchangeRateCurrent()` return underlying (e.g. 6 dp) and internal (18 dp) scale results correspondingly. 

## Vulnerability Detail

In the same time these functions have to follow the same convention, say both to have 18 dp, as they to be used interchangeably in any downstream integrations, by their nature differing in the additional computation costs and exchange rate value recency only.

## Impact

The downstream integrations using UToken's `exchangeRateStored()`, that outputs 6 dp results, will be broken. Since it's a misalignment of the expected exchange rate scale by magnitudes it will likely to have an accounting mismatch and monetary loss impact for those systems.

## Code Snippet

UToken exchange rate generally speaking shouldn't be scaled with underlying decimals, i.e. it has to follow a convention of its own, e.g. since UToken has fixed 18 dp, both versions of exchange rate can also have fixed 18 dp, while now it's only `exchangeRateCurrent()` behaves this way (`_exchangeRateStored()` returns 18 dp value):

[UToken.sol#L550-L561](https://github.com/sherlock-audit/2024-06-union-finance-update-2/blob/main/union-v2-contracts/contracts/market/UToken.sol#L550-L561)

```solidity
    function exchangeRateStored() public view returns (uint256) {
>>      return decimalReducing(_exchangeRateStored(), underlyingDecimal);
    }

    /**
     * @notice Accrue interest then return the up-to-date exchange rate
     * @return Calculated exchange rate scaled by 1e18
     */
    function exchangeRateCurrent() public nonReentrant returns (uint256) {
        if (!accrueInterest()) revert AccrueInterestFailed();
>>      return _exchangeRateStored();
    }
```

Also, `exchangeRateStored()` and `exchangeRateCurrent()` have to be aligned, i.e. their results need to be similarly scaled as these functions difference has nothing to do with decimals, being saved or live value of the same exchange rate state variable.

## Tool used

Manual Review

## Recommendation

Consider returning 18 dp figure in `exchangeRateStored()`, e.g.:

[UToken.sol#L550-L552](https://github.com/sherlock-audit/2024-06-union-finance-update-2/blob/main/union-v2-contracts/contracts/market/UToken.sol#L550-L552)

```diff
    function exchangeRateStored() public view returns (uint256) {
-       return decimalReducing(_exchangeRateStored(), underlyingDecimal);
+       return _exchangeRateStored();
    }
```

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/unioncredit/union-v2-contracts/pull/178

**Comment by dmitriia** [comment]
> The protocol team fixed this issue in the following PRs/commits: [unioncredit/union-v2-contracts#178](https://github.com/unioncredit/union-v2-contracts/pull/178)

Fix looks ok
