### ISSUE TITLE
smbv-1923 - Share inflation attack while depositing tokens and minting Utoken  in `UToken.sol::mint()`

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-union-finance-update-2-judging#119]
smbv-1923

High

# Share inflation attack while depositing tokens and minting Utoken  in `UToken.sol::mint()`

## Summary
- Share inflation attack while depositing tokens and minting Utoken  in `UToken.sol::mint()`

## Vulnerability Detail
- When Total Supply of  UToken is Zero then this attack can be initiated.
- Attacker deposit few underlying tokens through `UToken.sol::mint()`
- Attacker then borrow these assets through `borrow()`
- Then attacker waits till one block has been minted so that atleast 1 wei of interest has been generated.
- After this attacker repay the amount and interest using `repayBorrow()`
- So here now totalAssets > totalShares due to interest being accrued and added in totalAssets.
- After this they redeem all but  make remains 1wei of shares.
- So contract state would be UToken shares = 1 and totalAssets(Underlying token) >=2 due to rounding.
- Now attacker inflate the price of share .
- Now in a loop attacker continues to deposit asset till he get's his target price.
- Attacker every time deposits (totalAssests - 1) assets so that each he would be minting zero shares due to rounding down.
- So in for loop the UToken shares would remain at 1 and totalAssests would increase exponentially and would reach to target price of attacker.
## Impact
- Normal user whoever deposits assests less than totalAssests(target price which is inflated by attacker) would be minted zero number of shares .
- So total loss of funds for user.
## Code Snippet
https://github.com/unioncredit/union-v2-contracts/blob/master/contracts/market/UToken.sol#L747
## Tool used

Manual Review

## Recommendation
- Use ERC4626 upgradeable version for calculation of share mechanism.
- Burn 1000 wei of assets to dead address

Duplicate of #42

**Comment by WangSecurity** [comment]
Issue is invalidated based on the discussion below report #42
