### ISSUE TITLE
Bigsam - Interest Free Loans can be obtained from the Contract

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-union-finance-update-2-judging#29]
Bigsam

High

# Interest Free Loans can be obtained from the Contract

## Summary

When a loan is written off the interest and the interest index are not updated accordingly. Write-off is another form of repayment of bad debt. in the former audit, a vulnerability was observed because lastrepay was not updated. 

https://github.com/sherlock-audit/2022-10-union-finance-judging/issues/115

This report identifies another vulnerability because interest is not calculated and updated accordingly.
A Malicious user can deliberately borrow with no intention of repaying, forcing the debt writeoff to be called but when this is called all the debt of the User is cleared but the owed interest is not accounted for hence the contract loses out of its revenue.

The interest is not written off but the contract fails to store this value hence interest is not applied and thus the Malicious user can borrow again without repaying any interest on the former loan. Thus this can be repeated over and over and over again.

## Vulnerability Detail

When the loan has been written off the user can borrow another amount with loan. interest = 0 since it was not set when the debt was written-off, thereby a malicious user can avoid paying any interest by neglecting the principal/loan.

```solidity
    function debtWriteOff(address borrower, uint256 amount) external override whenNotPaused onlyUserManager {
        if (amount == 0) revert AmountZero();
        uint256 actualAmount = decimalScaling(amount, underlyingDecimal);

        uint256 oldPrincipal = _getBorrowed(borrower);
        uint256 repayAmount = actualAmount > oldPrincipal ? oldPrincipal : actualAmount;

        accountBorrows[borrower].principal = oldPrincipal - repayAmount;
        _totalBorrows -= repayAmount;

        if (repayAmount == oldPrincipal) {
            // If all principal is written off, we can reset the last repaid time to 0.
            // which indicates that the borrower has no outstanding loans.
            accountBorrows[borrower].lastRepay = 0;
        }
    }
```
From the above implementation it can be noted that interest and interestrateindex are not set. 

Because interest is not set in the wrote-off function, when calculating interest is Called it will return zero once the debt is written off.

```solidity
  function calculatingInterest(address account) public view override returns (uint256) {
        return decimalReducing(_calculatingInterest(account), underlyingDecimal);
    } 
```

With this clean slate a Malicious user is encouraged to borrow again, Knowing fully well that he is not going to repay the former interest. 

```solidity
        function borrow(address to, uint256 amount) external override onlyMember(msg.sender) whenNotPaused nonReentrant {
         ..................................................
   @audit >> Former interest should be reflected here but it returns 0>>    uint256 borrowedAmount = borrowBalanceStoredInternal(msg.sender);

        // Initialize the last repayment date to the current block timestamp
        if (getLastRepay(msg.sender) == 0) {
            accountBorrows[msg.sender].lastRepay = getTimestamp();
        }

        // Withdraw the borrowed amount of tokens from the assetManager and send them to the borrower
        uint256 remaining = assetManagerContract.withdraw(underlying, to, amount);
        if (remaining > amount) revert WithdrawFailed();
        actualAmount -= decimalScaling(remaining, underlyingDecimal);

        fee = calculatingFee(actualAmount);
        uint256 accountBorrowsNew = borrowedAmount + actualAmount + fee;
        uint256 totalBorrowsNew = _totalBorrows + actualAmount + fee;
        if (totalBorrowsNew > _debtCeiling) revert AmountExceedGlobalMax();

        // Update internal balances
        accountBorrows[msg.sender].principal += actualAmount + fee;
        uint256 newPrincipal = _getBorrowed(msg.sender);

    @audit >> Interest is 0 >>       accountBorrows[msg.sender].interest = accountBorrowsNew - newPrincipal;

        accountBorrows[msg.sender].interestIndex = borrowIndex;
        _totalBorrows = totalBorrowsNew;

   
    }
```

## Impact
Interest is not updated on loan write-off hence principal is cleared by the staker but interest is not set and the borrower successfully evades payments and goes free with an interest-free loan.
## Code Snippet

https://github.com/sherlock-audit/2024-06-union-finance-update-2/blob/main/union-v2-contracts/contracts/market/UToken.sol#L785-L800

https://github.com/sherlock-audit/2024-06-union-finance-update-2/blob/main/union-v2-contracts/contracts/market/UToken.sol#L611

https://github.com/sherlock-audit/2024-06-union-finance-update-2/blob/main/union-v2-contracts/contracts/market/UToken.sol#L624

https://github.com/sherlock-audit/2024-06-union-finance-update-2/blob/main/union-v2-contracts/contracts/market/UToken.sol#L517-L518

https://github.com/sherlock-audit/2024-06-union-finance-update-2/blob/main/union-v2-contracts/contracts/market/UToken.sol#L637

https://github.com/sherlock-audit/2024-06-union-finance-update-2/blob/main/union-v2-contracts/contracts/market/UToken.sol#L642-L644

https://github.com/sherlock-audit/2024-06-union-finance-update-2/blob/main/union-v2-contracts/contracts/market/UToken.sol#L585

https://github.com/sherlock-audit/2024-06-union-finance-update-2/blob/main/union-v2-contracts/contracts/market/UToken.sol#L588

https://github.com/sherlock-audit/2024-06-union-finance-update-2/blob/main/union-v2-contracts/contracts/market/UToken.sol#L704-L710

## Tool used

Manual Review

## Recommendation

Set the interest and interate index before debt write-off to ensure that a user pays even if their debt(Principal) is written off

```solidity
      function debtWriteOff(address borrower, uint256 amount) external override whenNotPaused onlyUserManager {
        if (amount == 0) revert AmountZero();
      ++   if (!accrueInterest()) revert AccrueInterestFailed();
      ++   uint256 interest = _calculatingInterest(borrower);

        uint256 actualAmount = decimalScaling(amount, underlyingDecimal);

        uint256 oldPrincipal = _getBorrowed(borrower);
        uint256 repayAmount = actualAmount > oldPrincipal ? oldPrincipal : actualAmount;

        accountBorrows[borrower].principal = oldPrincipal - repayAmount;
        _totalBorrows -= repayAmount;

       ++  accountBorrows[borrower].interest= interest;
       ++  accountBorrows[borrower].interestIndex = borrowIndex

        if (repayAmount == oldPrincipal) {
            // If all principal is written off, we can reset the last repaid time to 0.
            // which indicates that the borrower has no outstanding loans.
            accountBorrows[borrower].lastRepay = 0;
         }
      } 
```

**Comment by Tomiwasa0** [comment]
Thanks for judging @mystery0x,

I believe The intended design of debt write off is to clear principal debt and not interest. If this attacker borrows a huge fund (1 million USDC) available with an interest of 100,000 who bears the interest? 
Based on the docs, 

https://docs.union.finance/developers/core/usermanager#logdebtwriteoff:~:text=adjusting%20balances%20in%20the%20AssetManager%20and%20the%20UToken%20to%20repay%20the%20principal
Principal is the main concern of debt write of
https://docs.union.finance/protocol-overview/faq#:~:text=How%20do%20i%20get%20the%20money%20back%20if%20they%20dont%20pay%20me%20back%3F%20%2D%20you%20don%27t%2C%20this%20is%20the%20risk%20of%20credit.

The risk of borrowing and lending should not affect the protocol's earned profit.

**Comment by trachevgeorgi** [comment]
Escalate
On behalf of @Tomiwasa0

**Comment by sherlock-admin3** [comment]
> Escalate
> On behalf of @Tomiwasa0 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by mystery0x** [comment]
It's an intended design regardless with `onlyUserManager` visibility on `debtWriteOff()`.

**Comment by Tomiwasa0** [comment]
Based on the rules -
>> doesn't imply any loss of funds
https://docs.sherlock.xyz/audits/judging/judging#:~:text=Design%20decisions%20are%20not%20valid%20issues.%20Even%20if%20the%20design%20is%20suboptimal%2C%20but%20doesn%27t%20imply%20any%20loss%20of%20funds%2C%20these%20issues%20are%20considered%20informational.

Funds for stakers and liquidity provided are lost here. hence should be reconsidered.

**Comment by WangSecurity** [comment]
As I understand it works exactly as it should since the debt is written off when the borrower doesn't repay the loan for too long. Hence, technically it means the borrower doesn't have a loan now, so they don't have interest. I'll ask the sponsor if it works as they intended, and giving time to @Tomiwasa0 to correct me.

**Comment by Tomiwasa0** [comment]
Thanks for the update Sir Wang @WangSecurity , Would go with the final verdict and sponsor's view.

Just to point out 

Yes the debt write off clears the principal debt as intended,

But  the interest accumulated before this debt's principal is cleared is not accounted for,
 
According to repay this interest is a revenue to the contract and Utoken minters.

```solidity
// Define a function to calculate the distribution of interest
function calculateInterestDistribution(uint256 interest, uint256 reserveFactorMantissa) public pure returns (uint256 toReserveAmount, uint256 toRedeemableAmount) {
    // WAD is typically used as a constant for scaling factors in Solidity.
    uint256 WAD = 10**18;

    // Calculate the amount of interest to be sent to the reserves
    toReserveAmount = (interest * reserveFactorMantissa) / WAD;

    // Calculate the amount of interest to be added to the redeemable amount
    toRedeemableAmount = interest - toReserveAmount;

    // Return the calculated values
    return (toReserveAmount, toRedeemableAmount);
}
```

This rewards are lost.

Based on Compound implementation interest on fees is always collected because users are liquidated also Exactly protocol has a function that writes off debt but the fee/interest is also removed from the borrower's EARNINGS.

Exactly implementation- https://github.com/sherlock-audit/2024-07-exactly-stacking-contracts/blob/3eb87e3edf3bcd57c4cc1c6a73e8255f575b76de/protocol/contracts/Market.sol#L624-L627 

Compound - https://github.com/compound-finance/compound-protocol/blob/a3214f67b73310d547e00fc578e8355911c9d376/contracts/CToken.sol#L694-L700

**Comment by WangSecurity** [comment]
Let's avoid using other protocols as examples, each protocol has their own design and they have different intentions. Hence, the fact that exactly or compound do this one way, but Union in another way doesn't mean it's an issue.

I believe it's the design of the protocol to not repay the interest here, since the result of this function is to make the borrower to not have any outstanding loans. Also, as the say the docs you've sent in the escalation comment, the FAQ says that you don't get the money back if the borrower doesn't pay me. Hence, I believe it also aligns here.

Planning to reject the escalation and leave the issue as it is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [trachevgeorgi](https://github.com/sherlock-audit/2024-06-union-finance-update-2-judging/issues/29/#issuecomment-2241270617): rejected
