### ISSUE TITLE
JuggerNaut63 - Unsafe Use of 'transfer()'/'transferFrom()' on ERC20

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-union-finance-update-2-judging#57]
JuggerNaut63

Medium

# Unsafe Use of 'transfer()'/'transferFrom()' on ERC20

## File Location
- https://github.com/sherlock-audit/2024-06-union-finance-update-2/blob/main/union-v2-contracts/contracts/peripheral/VouchFaucet.sol#L95
- https://github.com/sherlock-audit/2024-06-union-finance-update-2/blob/main/union-v2-contracts/contracts/peripheral/VouchFaucet.sol#L124

## Summary
Direct use of the _'transfer()'_ and _'transferFrom()'_ functions in ERC20 contracts may introduce vulnerabilities, especially in tokens that are not fully compliant with ERC20 standards. This can cause transaction failure and damage the reliability of the contract.

## Vulnerability Detail
In the contract _'VouchFaucet.sol'_, a direct use of the _'transfer()'_ function was found to transfer ERC20 tokens. This function does not always return a boolean value, which can cause failure when a token not compliant with the ERC20 standard is called.

## Impact
- loss of tokens
- transaction failure
- can damage the integrity and reliability of the contract

## Code Snippet
L95
`        IERC20(token).transfer(msg.sender, amount);`

L124
`        IERC20(token).transfer(to, amount);`

## Tool used

Manual Review

## Recommendation
Use the SafeERC20 library from OpenZeppelin which provides the _'safeTransfer()'_ and _'safeTransferFrom()'_ functions. These functions check the results of the transfer operation and ensure that the transaction is successful or return appropriate errors if it fails. Here are the recommended fixes:
```solidity
// Add SafeERC20 import from OpenZeppelin
import "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";

// Use the SafeERC20 library
using SafeERC20 for IERC20;

L95
IERC20(token).safeTransfer(msg.sender, amount);

L124
IERC20(token).safeTransfer(to, amount);
```

Duplicate of #22

**Comment by WangSecurity** [comment]
While this is a sufficient duplicate according to the rules, since it says that tokens without a return value will make the transaction fail, I want to give an advice, elaborate more on how the issue would happen and which tokens exactly would cause it, i.e. USDT which is in-scope.
