### ISSUE TITLE
MohammedRizwan - users can not repay their debts if repay functions are paused and would need to pay forced debt incured during pause period

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-union-finance-update-2-judging#74]
MohammedRizwan

Medium

# users can not repay their debts if repay functions are paused and would need to pay forced debt incured during pause period

## Summary
users can not repay their debts if repay functions are paused and would need to pay forced debt incured during pause period

## Vulnerability Detail
The following `Union` contracts have repay functions which allows a borrower to repay debt. 

1) `UDai.repayBorrowWithPermit()`:

```solidity
    function repayBorrowWithPermit(
        address borrower,
        uint256 amount,
        uint256 nonce,
        uint256 expiry,
        uint8 v,
        bytes32 r,
        bytes32 s
    ) external whenNotPaused {

       . . . some code . . . 

        uint256 interest = calculatingInterest(borrower);
        _repayBorrowFresh(msg.sender, borrower, decimalScaling(amount, underlyingDecimal), interest);
    }
```

2) `UErc20.repayBorrowWithERC20Permit()`:

```solidity
    function repayBorrowWithERC20Permit(
        address borrower,
        uint256 amount,
        uint256 deadline,
        uint8 v,
        bytes32 r,
        bytes32 s
    ) external whenNotPaused {

       . . . some code . . . 

        uint256 interest = calculatingInterest(borrower);
        _repayBorrowFresh(msg.sender, borrower, decimalScaling(amount, underlyingDecimal), interest);
    }
```

3) `UToken.repayBorrow()`:

```solidity
    function repayBorrow(address borrower, uint256 amount) external override whenNotPaused nonReentrant {

       . . . some code . . . 

        uint256 interest = _calculatingInterest(borrower);
        _repayBorrowFresh(msg.sender, borrower, actualAmount, interest);
    }
```

All of the above function has implemented the `whenNotPaused` modifier, which will prevent the function from being used if the contract is paused.

The problem is that the usage of these repay functions should not be prevented because if user is unable to repay their debts, they would need to pay higher debts while the the `Union` contracts are paused due incuring debts.

All of the above repay functions calls internal function `_calculatingInterest()` which will return the interest for the borrower account. `_calculatingInterest()` is implemented as:

```solidity
    function _calculatingInterest(address account) private view returns (uint256) {
        BorrowSnapshot memory loan = accountBorrows[account];

        if (loan.principal == 0) {
            return 0;
        }

        uint256 borrowRate = borrowRatePerSecond();
@>        uint256 currentTimestamp = getTimestamp();
@>        uint256 timeDelta = currentTimestamp - accrualTimestamp;   @audit // does not exclude the pause period
        uint256 simpleInterestFactor = borrowRate * timeDelta;
        uint256 borrowIndexNew = (simpleInterestFactor * borrowIndex) / WAD + borrowIndex;

        uint256 principalTimesIndex = (loan.principal + loan.interest) * borrowIndexNew;
        uint256 balance = principalTimesIndex / loan.interestIndex;

        return balance - _getBorrowed(account);
    }
```

`_calculatingInterest()` calculated interest on time difference based on `currentTimestamp - accrualTimestamp` to get the interest over the passed time period. The interest rate depends on the time passed which means higher the time passed, then the higher interest has to be paid by the users.

Therefore, when the contracts are paused the user interest is still accuring and the user has to pay unnecessary high amount than he had to pay earlier. This introduces an unnecesary risk to users by preventing them to repay their debts.

## Impact
Interest is still accuring when the `Union` contract repay is paused, it will force user to incur debts and pay higher debts than he had to earlier due to repay pause, While calculating interest, paused period is not excluded in `timeDelta` calculations so users are forced to pay higher interest.

## Code Snippet
https://github.com/sherlock-audit/2024-06-union-finance-update-2/blob/main/union-v2-contracts/contracts/market/UToken.sol#L679

https://github.com/sherlock-audit/2024-06-union-finance-update-2/blob/main/union-v2-contracts/contracts/market/UErc20.sol#L15

https://github.com/sherlock-audit/2024-06-union-finance-update-2/blob/main/union-v2-contracts/contracts/market/UDai.sol#L17

## Tool used
Manual Review

## Recommendation
There can two solutions to mitigate the issue: 

1) Remove the `whenNotPaused` from repay functions to allow users to repay anytime irrespective of pause of contracts, OR
2) Do not consider the pause period when calculating the interest

**Comment by 0xRizwan** [comment]
I believe, this issue is not correctly judged.

@mystery0x 
> Intended design and commonly known issue

Its not mentioned in contest readme. It can be seen the below readme questions and their answers does not explicitely mentions about this issue

> Please discuss any design choices you made.
If someone doesn't repay the person that underwrote them will not be able to get money back. This is not a bug this is credit.

> Please list any known issues and explicitly state the acceptable risks for each known issue.
n/a

> Are there any limitations on values set by admins (or other roles) in the codebase, including restrictions on array lengths?
No

> For permissioned functions, please list all checks and requirements that will be made before calling the function.
n/a

Based on the above readme information, it can be understood that this issue is not known to protocol team and its NOT a intended design.

Further as per sherlock [rule](https://github.com/sherlock-protocol/sherlock-v2-docs/blob/e7dc89270b05f8d2fcee69dc4204c7a2b8fb4cf9/audits/judging/judging/README.md#iii-sherlocks-standards), i believe this issue should be assigned medium severity.

> The protocol team can use the README (and only the README) to define language that indicates the codebase's restrictions and/or expected functionality. Issues that break these statements, irrespective of whether the impact is low/unknown, will be assigned Medium severity.

**Comment by 0xMR0** [comment]
Escalate 

on behalf of @0xRizwan

**Comment by sherlock-admin3** [comment]
> Escalate 
> 
> on behalf of @0xRizwan 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by mystery0x** [comment]
This parallels the scenario where a healthy position during the paused state could end up liquidatable when `unpause()` is triggered due to price fluctuations. PAUSER should be trusted and well aware of avoiding these shortcomings.

**Comment by WangSecurity** [comment]
The escalator is correct that the judging rules should apply since there is no specific info in the README about this issue. The following rule applies here:

> An admin action can break certain assumptions about the functioning of the code. Example: Pausing a collateral causes some users to be unfairly liquidated or any other action causing loss of funds. This is not considered a valid issue.

Planning to reject the escalation and leave the issue as it is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xMR0](https://github.com/sherlock-audit/2024-06-union-finance-update-2-judging/issues/74/#issuecomment-2241988064): rejected
