### ISSUE TITLE
trachev - Functions that require permits can be called only by the permit creator

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-union-finance-update-2-judging#84]
trachev

Medium

# Functions that require permits can be called only by the permit creator

## Summary
`repayBorrowWithPermit`, `repayBorrowWithERC20Permit`, `registerMemberWithPermit`, `stakeWithPermit` and `stakeWithERC20Permit` are allowed to be called by the permit creator only. No other addresses will be allowed to execute these functions on behalf of the signer, which is the sole purpose of the functions that require permits.

## Vulnerability Detail
Let's take a look at the `repayBorrowWithPermit` function:
```solidity
function repayBorrowWithPermit(
        address borrower,
        uint256 amount,
        uint256 nonce,
        uint256 expiry,
        uint8 v,
        bytes32 r,
        bytes32 s
    ) external whenNotPaused {
        IDai erc20Token = IDai(underlying);
        erc20Token.permit(msg.sender, address(this), nonce, expiry, true, v, r, s);

        if (!accrueInterest()) revert AccrueInterestFailed();
        uint256 interest = calculatingInterest(borrower);
        _repayBorrowFresh(msg.sender, borrower, decimalScaling(amount, underlyingDecimal), interest);
    }
```

The function calls `erc20Token.permit`, supplying `msg.sender` as the 'owner' of the permit and `address(this)` as the 'spender' of the permit.

Therefore, the only way the functions can be successful is when the creator of the permit is the same as the `msg.sender`. However, the sole purpose of the permit is to allow the permit creator to sign the approve data, so that the signature can be used by another address to execute calls on behalf of the permit creator.

Here is the same issue found in a recent competition: https://code4rena.com/reports/2023-07-pooltogether#m-25-depositwithpermit-and-mintwithpermit-are-allowed-to-be-called-by-the-permit-creator-only

## Impact
As a result, `repayBorrowWithPermit`, `repayBorrowWithERC20Permit`, `registerMemberWithPermit`, `stakeWithPermit` and `stakeWithERC20Permit` will not function as intended and will essentially not fulfill their purpose.

## Code Snippet

https://github.com/sherlock-audit/2024-06-union-finance-update-2/blob/main/union-v2-contracts/contracts/user/UserManager.sol#L711

https://github.com/sherlock-audit/2024-06-union-finance-update-2/blob/main/union-v2-contracts/contracts/market/UDai.sol#L19

https://github.com/sherlock-audit/2024-06-union-finance-update-2/blob/main/union-v2-contracts/contracts/user/UserManagerERC20.sol#L27

https://github.com/sherlock-audit/2024-06-union-finance-update-2/blob/main/union-v2-contracts/contracts/user/UserManagerDAI.sol#L29

https://github.com/sherlock-audit/2024-06-union-finance-update-2/blob/main/union-v2-contracts/contracts/market/UErc20.sol#L17

## Tool used

Manual Review

## Recommendation
Instead of `msg.sender`, use another user-supplied address, for example `owner`:
```solidity
function repayBorrowWithPermit(
        address owner,
        address borrower,
        uint256 amount,
        uint256 nonce,
        uint256 expiry,
        uint8 v,
        bytes32 r,
        bytes32 s
    ) external whenNotPaused {
        IDai erc20Token = IDai(underlying);
        erc20Token.permit(owner, address(this), nonce, expiry, true, v, r, s);

        if (!accrueInterest()) revert AccrueInterestFailed();
        uint256 interest = calculatingInterest(borrower);
        _repayBorrowFresh(owner, borrower, decimalScaling(amount, underlyingDecimal), interest);
    }
```

**Comment by trachevgeorgi** [comment]
Escalate
This issue has been incorrectly excluded. As I have stated above this issue causes all permit functions to become useless, which by the Sherlock criteria should be a valid issue: 2. Breaks core contract functionality, rendering the contract useless or leading to loss of funds.

**Comment by sherlock-admin3** [comment]
> Escalate
> This issue has been incorrectly excluded. As I have stated above this issue causes all permit functions to become useless, which by the Sherlock criteria should be a valid issue: 2. Breaks core contract functionality, rendering the contract useless or leading to loss of funds.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by mystery0x** [comment]
Will have the sponsor look into this whether or not `msg.sender` has been deliberately inputted as intended in the protocol context.

**Comment by WangSecurity** [comment]
As far as I'm aware this is one of the viable implementations of the permit functions and it can be used to save gas for users. Additionally, this issue doesn't lead to a loss of funds and the users can still use other non-permit functions and use protocol freely. While it limits the ability to have others call functions on your behalf, I believe it's an opportunity loss and low/info.

Hence, planning to reject the escalation and leave the issue as it is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [trachevgeorgi](https://github.com/sherlock-audit/2024-06-union-finance-update-2-judging/issues/84/#issuecomment-2240078983): rejected
